server:
  port: 9090
spring:
  datasource:
    password: ismail@123
    url: jdbc:mysql://localhost:3306/batchdemo?createDatabaseIfNotExist=true
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        formatsql: true
        showsql: true
  batch:
    jdbc:
      initialize-schema: always
