spring:
  h2:
    console:
      enabled: true
      path: /h2_console
  datasource:
    url: jdbc:h2:file:~/h2/demodbnew
    username: root
    password:
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
      dialect: org.hibernate.dialect.H2Dialect
      jakarta:
      persistence:
      jdbc:
      external:
      api:
      url: https://jsonplaceholder.typicode.com

logging:
  level:
    root: info
    com:
      jpa:
        transaction:
          springTransaction: debug
  path: logs
  file: ${logging.path}/log.log
  pattern:
    file: "%d{dd-MM-yyyy HH:mm:ss.SSS} [%thread] %-5level %logger{36}.%M - %msg%n"
    console: "%d{dd-MM-yyyy HH:mm:ss.SSS} %magenta([%thread]) %highlight(%-5level) %logger{36}.%M - %msg%n"
